Description: Downloads the latest versions of Docker (arm and intel).
Identifier: com.mhrono.recipes.download.Docker-Universal
MinimumVersion: '2.3'

Input:
  NAME: Docker

Process:
  - Processor: URLTextSearcher
    Arguments:
      re_pattern: '((\w+):\/\/(\S*)(arm64)(\S*)(dmg)(?=\?))'
      result_output_var_name: match
      url: 'https://www.docker.com/get-started'

  - Processor: URLDownloaderPython
    Arguments:
      filename: '%NAME%-arm64.dmg'
      download_dir: '%RECIPE_CACHE_DIR%/downloads'
      url: '%match%'

  - Processor: URLTextSearcher
    Arguments:
      re_pattern: '((\w+):\/\/(\S*)(amd64)(\S*)(dmg)(?=\?))'
      result_output_var_name: match
      url: 'https://www.docker.com/get-started'

  - Processor: URLDownloaderPython
    Arguments:
      filename: '%NAME%-x86_64.dmg'
      download_dir: '%RECIPE_CACHE_DIR%/downloads'
      url: '%match%'

  - Processor: EndOfCheckPhase

  - Processor: Versioner
    Arguments:
      input_plist_path: '%RECIPE_CACHE_DIR%/downloads/%NAME%-arm64.dmg/Docker.app/Contents/Info.plist'
      plist_version_key: 'CFBundleShortVersionString'

  - Processor: CodeSignatureVerifier
    Arguments:
      input_path: '%RECIPE_CACHE_DIR%/downloads/%NAME%-arm64.dmg/Docker.app'
      requirement: anchor apple generic and identifier "com.docker.docker" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "9BNSXJN65R")
      deep_verification: True
      strict_verification: True

  - Processor: CodeSignatureVerifier
    Arguments:
      input_path: '%RECIPE_CACHE_DIR%/downloads/%NAME%-x86_64.dmg/Docker.app'
      requirement: anchor apple generic and identifier "com.docker.docker" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "9BNSXJN65R")
      deep_verification: True
      strict_verification: True
